version: '3.8'

services:
  backend:
    build: .
    container_name: fashionstore_backend
    ports:
      - "8000:8000"
    volumes:
      # Montar base de datos SQLite y uploads para que persistan a los reinicios de Docker
      - ./fashionstore.db:/app/fashionstore.db
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    environment:
      - ENVIRONMENT=production
    restart: always
    networks:
      - fashion_net

networks:
  fashion_net:
    name: fashion_net
